name: PSI SMEB
url: http://smeb.jayperryworks.com
baseurl: 
permalink: none

markdown: redcarpet
pygments: true

exclude: ["README.md", "config.rb", ".sublime-project", ".sublime-workspace", "Guardfile", "Gemfile", "Gemfile.lock", ".sass-cache"]