name: PSI SMEB
url: http://clients.jayperryworks.com/psi-smeb
baseurl: 
permalink: none

markdown: redcarpet
highlighter: true

exclude: ["README.md", "config.rb", "scratch.html", "psi-smeb-updates.sublime-project", "psi-smeb-updates.sublime-workspace", "Guardfile", "Gemfile", "Gemfile.lock", ".sass-cache"]


assets: http://psilearning.org/jay
serverurl: /resources/social-marketing-evidence-base