name: PSI SMEB
url: http://psi.hfwebdev.com
baseurl: /resources/social-marketing-evidence-base
permalink: none

markdown: redcarpet
pygments: true

exclude: ["README.md", "config.rb", "scratch.html", "psi-smeb-updates.sublime-project", "psi-smeb-updates.sublime-workspace", "Guardfile", "Gemfile", "Gemfile.lock", ".sass-cache"]


assets: http://psilearning.org/jay